version: "3.8"

name: trpo-project

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - prod
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    links:
      - postgres
      - minio
    environment:
      - DB_USER=nifle3
      - DB_PASSWORD=12345
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=student_records
      - DB_SSL=disable
      - FS_USER=nifle
      - FS_PASSWORD=nilfepassword
      - FS_END_POINT=minio:9000
      - SERVER_PORT=8080
      - SERVER_HOST=localhost

  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: nifle3
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: student_records
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgres
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod
    healthcheck:
      test: pg_isready -U nifle3 -d student_records
      interval: 10s
      timeout: 3s
      retries: 3

  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data_1:/data1
      - minio_data_2:/data2
    networks:
      - prod
    environment:
      MINIO_ROOT_USER: nifle
      MINIO_ROOT_PASSWORD: nilfepassword
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-mc:
    container_name: minio-mc
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/document;
      /usr/bin/mc policy set public myminio/document;
      /usr/bin/mc mb myminio/student-photo;
      /usr/bin/mc policy set public myminio/student-photo;
      /usr/bin/mc mb myminio/application;
      /usr/bin/mc policy set public myminio/application;
      exit 0;"

networks:
  prod:
    driver: bridge

volumes:
  postgres_data:
  minio_data_1:
  minio_data_2:
