version: "3.8"

name: trpo-project

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - prod
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      DB_USER: "nifle3"
      DB_PASSWORD: "12345"
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_NAME: "student_records"
      DB_SSL: "false"
      FS_USER: "nifle"
      FS_PASSWORD: "nilfepassword"
      FS_END_POINT: "localhost:9000"
      SERVER_PORT: "8080"
      SERVER_HOST: "localhost"

  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: 'nifle3'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'student_records'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod

  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data_1:/data1
      - minio_data_2:/data2
    networks:
      - prod
    environment:
      MINIO_ROOT_USER: "nifle"
      MINIO_ROOT_PASSWORD: "nilfepassword"
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  prod:
    driver: bridge

volumes:
  postgres_data:
  minio_data_1:
  minio_data_2:
