version: "3.8"

name: trpo-project

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - prod
      - test
    restart: unless-stopped
    ports:
      - '8080:8080'

  database:
    container_name: database
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: 'nifle3'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'student_records'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod

  database_test:
    container_name: database_test
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: 'nifle3'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'student_records'
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/data/postgres
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test

  minio:
    container_name: minio
    image: bitnami/minio:2024.4.18
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - prod
    environment:
      - MINIO_ROOT_USER=nifle3
      - MINIO_ROOT_PASSWORD=12345

networks:
  prod:
    driver: bridge
  test:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local