version: "3.8"

name: trpo-project

services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: Dockerfile
    networks:
      - prod
    restart: unless-stopped
    ports:
      - '8080:8080'

  database:
    container_name: database
    image: postgres:16.2

networks:
  prod:
    driver: bridge
